### ISSUE TITLE
python get wrong

### ISSUE THREAD

**Issue by kk66668** [tvogiannou/hephaestus#1]
I run “python example-render_tri_mesh.py” get these error messages
Xlib: extension "NV-GLX" missing on display "localhost:11.0".
python: /opt/mnt_ssd2/kk/head2head-master/hephaestus-master/hephaestus/../external/vulkan-1.2.133/vulkan/vulkan.hpp:12587: typename vk::ResultValueType::type vk::createResultValue(vk::Result, T&, const char*) [with T = std::vectorvk::PhysicalDevice; typename vk::ResultValueType::type = vk::ResultValue<std::vectorvk::PhysicalDevice >]: Assertion `result == Result::eSuccess' failed.
Aborted (core dumped)

**Comment by tvogiannou** [comment]
This looks like a driver issue. Could you give more details on what platform & GPU you are using?
What does vulkaninfo return?

**Comment by kk66668** [comment]
Thank you for reply！my os is ubuntu16.04. GPU are v100 32g *8
vulkaninfo return :
$ vulkaninfo
===========
VULKAN INFO
===========

Vulkan API Version: 1.0.61

INFO: [loader] Code 0 : Found ICD manifest file /etc/vulkan/icd.d/nvidia_icd.json, version "1.0.0"
INFO: [loader] Code 0 : Found ICD manifest file /usr/share/vulkan/icd.d/radeon_icd.x86_64.json, version "1.0.0"
INFO: [loader] Code 0 : Found ICD manifest file /usr/share/vulkan/icd.d/intel_icd.x86_64.json, version "1.0.0"
Xlib:  extension "NV-GLX" missing on display "localhost:25.0".

Instance Extensions:
====================
Instance Extensions     count = 14
        VK_KHR_display                      : extension revision 21
        VK_KHR_external_fence_capabilities  : extension revision  1
        VK_KHR_external_memory_capabilities : extension revision  1
        VK_KHR_external_semaphore_capabilities: extension revision  1
        VK_KHR_get_physical_device_properties2: extension revision  1
        VK_KHR_get_surface_capabilities2    : extension revision  1
        VK_KHR_surface                      : extension revision 25
        VK_KHR_xcb_surface                  : extension revision  6
        VK_KHR_xlib_surface                 : extension revision  6
        VK_EXT_acquire_xlib_display         : extension revision  1
        VK_EXT_debug_report                 : extension revision  9
        VK_EXT_direct_mode_display          : extension revision  1
        VK_EXT_display_surface_counter      : extension revision  1
        VK_KHR_wayland_surface              : extension revision  6
/build/vulkan-YO5iw0/vulkan-1.0.61.1+dfsg1/demos/vulkaninfo.c:1722: failed with VK_ERROR_INITIALIZATION_FAILED

**Comment by tvogiannou** [comment]
It does look like a driver issue.
You can find more details on how to install drivers & Vulkan for Ubuntu from [this link](https://linuxconfig.org/install-and-test-vulkan-on-linux)

**Comment by tvogiannou** [comment]
Closing as there is no update on this.
Feel free to reopen if needed.
